#!/bin/bash

if [[ $_ = $0 ]]
then
  echo "You must source this script!"
  exit 1
fi

echo "Killing gpg-agent"
killall gpg-agent

echo "Unsetting env vars"
unset GPG_AGENT_INFO SSH_AGENT_PID SSH_AUTH_SOCK

echo "Reinstating SSH_AUTH_SOCK from /tmp/previous_auth_sock"
export SSH_AUTH_SOCK="$(cat /tmp/previous_auth_sock)"
