#!/bin/bash

if [[ $_ = $0 ]]
then
  echo "You must source this script!"
  exit 1
fi

ttl=32400 # 9 hours

echo "Killing ssh-agent and gpg-agent"
killall ssh-agent gpg-agent

echo "Unsetting env vars"
unset GPG_AGENT_INFO SSH_AGENT_PID SSH_AUTH_SOCK

echo "Starting new gpg-agent with SSH support"
eval "$(gpg-agent --daemon --enable-ssh-support --default-cache-ttl $ttl --default-cache-ttl-ssh $ttl)"
